apiVersion: v1
kind: Service
metadata:
  name: belong-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
    - targetPort: 443
      port: 443
  selector:
    matchLabels:
      app: belong-app